- name: Install docker packages
  remote_user: "{{ system_user }}"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  tags:
    - docker

- name: Add Docker s official GPG key
  remote_user: "{{ system_user }}"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Verify that we have the key with the fingerprint
  remote_user: "{{ system_user }}"
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker

- name: Set up the stable repository
  remote_user: "{{ system_user }}"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
  tags:
    - docker

- name: Update apt packages
  remote_user: "{{ system_user }}"
  apt:
    update_cache: yes
  tags:
    - docker

- name: Install docker
  remote_user: "{{ system_user }}"
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  #notify: Start docker on boot
  tags:
    - docker

- name: Add remote "ansible" user to "docker" group
  remote_user: "{{ system_user }}"
  user:
    name: "{{ system_user }}"
    group: "docker"
    append: yes
  tags:
    - docker

- name: Install docker-compose
  remote_user: "{{ system_user }}"
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'